(use-package smooth-scrolling)
(use-package magit)
(use-package marginalia)
(use-package consult)
(use-package embark)
(use-package embark-consult)
(use-package orderless)
(use-package projectile)
(use-package which-key)
(use-package git-gutter)
(use-package git-time-machine)
(use-package ripgrep)
(use-package all-the-icons)
(use-package vterm)
(use-package drag-stuff)
(use-package expand-region)


(provide 'aa/packages)
